# Generated by Django 3.2.4 on 2021-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210614_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
